<a href="https://colab.research.google.com/github/DK-77/CE059_Dhruv_Kathrotiya/blob/main/Lab1/Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import numpy as np
import pandas as pd

# New Section

In [7]:
#randomly initialize array
array1 = np.random.rand(2, 3)
array2 = np.random.rand(3, 2)
print(array1)
print(array2)

[[0.463922   0.85804662 0.02501104]
 [0.56537901 0.05574315 0.18886274]]
[[0.85109423 0.93776748]
 [0.43695055 0.61904749]
 [0.26624544 0.29867807]]


In [8]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[0.77642436 0.97369282]
 [0.55583166 0.62111087]]


In [9]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[0.7764243605099191, 0.9736928182631873], [0.5558316586803177, 0.621110866188896]]


In [10]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

0.35949409484963396


In [17]:
main_data = pd.read_csv("/content/drive/MyDrive/ML/Lab1/mtcars.csv")

In [18]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
