<a href="https://colab.research.google.com/github/DK-77/CE059_Dhruv_Kathrotiya/blob/main/Lab3/Lab3_Task1_CE059.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CE059 - Dataset 2, split 90-10, Label Encoding


In [31]:
import sklearn
from sklearn import preprocessing
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
import numpy as np
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/ML/Lab3/PracticeDataSets/Dataset2.csv')
print('\n Data \n', data)



 Data 
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [15]:
Outlook,Temp,Wind,Humidity,Class = [],[],[],[],[]

Outlook = data.iloc[:,0].values
print("\n\n Outlook \n\n",Outlook)

Temp = data.iloc[:,1].values
print("\n\n Temp \n\n",Temp)

Wind = data.iloc[:,2].values
print("\n\n Wind \n\n",Wind)

Humidity = data.iloc[:,3].values
print("\n Humidity \n\n",Humidity)

Class = data.iloc[:,4].values
print("\n Class \n\n",Class)




 Outlook 

 ['R' 'R' 'O' 'S' 'S' 'S' 'O' 'R' 'R' 'S' 'R' 'O' 'O' 'S']


 Temp 

 ['H' 'H' 'H' 'M' 'M' 'M' 'C' 'C' 'C' 'M' 'M' 'M' 'H' 'M']


 Wind 

 ['F' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'T']

 Humidity 

 ['Normal' 'High' 'Normal' 'Normal' 'Normal' 'Low' 'Normal' 'Normal' 'Low'
 'High' 'High' 'Low' 'Normal' 'Normal']

 Class 

 ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [17]:
#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
outlook_encoded=le.fit_transform(Outlook)
print("Outlook:" ,outlook_encoded)

temp_encoded=le.fit_transform(Temp)
print("\n\nTemp:" ,temp_encoded)

wind_encoded=le.fit_transform(Wind)
print("\n\nWind:" ,wind_encoded)

humidity_encoded=le.fit_transform(Humidity)
print("\n\nHumidity:" ,humidity_encoded)

class_encoded=le.fit_transform(Class)
print("\n\nClass:" ,class_encoded)

Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]


Temp: [1 1 1 2 2 2 0 0 0 2 2 2 1 2]


Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]


Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]


Class: [0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [39]:
#Combinig all features into single listof tuples
features=tuple(zip(outlook_encoded,temp_encoded,wind_encoded,humidity_encoded))
print("Features:",features)
targets = class_encoded
print("\n\nTargets:",targets)

Features: ((1, 1, 0, 2), (1, 1, 1, 0), (0, 1, 0, 2), (2, 2, 0, 2), (2, 2, 0, 2), (2, 2, 1, 1), (0, 0, 1, 2), (1, 0, 0, 2), (1, 0, 0, 1), (2, 2, 0, 0), (1, 2, 1, 0), (0, 2, 1, 1), (0, 1, 0, 2), (2, 2, 1, 2))


Targets: [0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [40]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(features,
                        targets, test_size = 0.10, random_state = 59)

In [41]:
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [42]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.5


In [43]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 1.0
recall: 0.5


In [44]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 0],
       [1, 1]])

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

ANS -> True

In [45]:
gnb.predict([[1,2,0,2]])

array([1])

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

ANS -> TRUE

In [46]:
gnb.predict([[2,0,1,0]])

array([1])